# Generated by Django 5.1.2 on 2024-11-14 23:14

import bsafeMain.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('start_time', models.TimeField(validators=[bsafeMain.models.validate_business_hours, bsafeMain.models.validate_time_slot])),
                ('end_time', models.TimeField(validators=[bsafeMain.models.validate_business_hours, bsafeMain.models.validate_time_slot])),
                ('service_type', models.CharField(choices=[('installation', 'Installation'), ('service', 'Service')], max_length=20)),
                ('additional_details', models.TextField(blank=True, null=True)),
                ('record_date', models.DateField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='bsafeMain.customer')),
                ('technicians', models.ManyToManyField(related_name='appointments', to='bsafeMain.technician')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('start_time__lt', models.F('end_time'))), name='start_time_before_end_time'), models.UniqueConstraint(fields=('date', 'start_time', 'end_time'), name='unique_appointment_time')],
            },
        ),
    ]
