# Generated by Django 5.1.2 on 2024-11-16 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsafeMain', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='technician',
            name='isSelected',
            field=models.BooleanField(default=False),
        ),
    ]
