# Generated by Django 5.1.2 on 2024-11-16 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bsafeMain', '0002_technician_isselected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technician',
            name='isSelected',
        ),
    ]
